# Generated by Django 2.1.5 on 2019-02-03 13:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='tel',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 3, 13, 11, 50, 839652)),
        ),
    ]
