# Generated by Django 2.1.5 on 2019-02-03 13:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0003_auto_20190203_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 3, 13, 58, 53, 12993, tzinfo=utc)),
        ),
    ]
