# Generated by Django 2.1.5 on 2019-02-03 19:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0004_auto_20190203_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='title',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 3, 19, 55, 24, 253563, tzinfo=utc)),
        ),
    ]
